from __future__ import annotations

import json
from pathlib import Path

from design_ir.models import (
    BoardIR,
    CanonicalDesignBundle,
    CircuitSpec,
    PatchPlan,
    SchematicIR,
    VerificationReport,
)

ROOT = Path(__file__).resolve().parents[3]
JSON_OUT = ROOT / "packages" / "schemas" / "json" / "canonical"
TS_OUT = ROOT / "packages" / "ui-shared" / "src" / "generated" / "canonical-types.ts"

MODELS = {
    "circuit-spec.schema.json": CircuitSpec,
    "schematic-ir.schema.json": SchematicIR,
    "board-ir.schema.json": BoardIR,
    "patch-plan.schema.json": PatchPlan,
    "verification-report.schema.json": VerificationReport,
    "canonical-design-bundle.schema.json": CanonicalDesignBundle,
}

TS_TEMPLATE = """/* Auto-generated by packages/design-ir/scripts/generate_schema_artifacts.py */

export type SchemaVersion = "1.0.0";

export type NamedObject = { name: string; description?: string | null };
export type CircuitSpec = {
  schema_version: SchemaVersion;
  product_name: string;
  summary: string;
  target_board_type: string;
  functional_blocks: NamedObject[];
  interfaces: NamedObject[];
  power_rails: NamedObject[];
  environmental_constraints: string[];
  mechanical_constraints: string[];
  cost_constraints: string[];
  manufacturing_constraints: string[];
  preferred_parts: string[];
  banned_parts: string[];
  open_questions: string[];
};

export type Symbol = { symbol_id: string; kind: string; library_ref?: string | null };
export type ComponentInstance = {
  instance_id: string;
  symbol_id: string;
  reference: string;
  value?: string | null;
  properties: Record<string, string>;
};
export type PinDirection = "input" | "output" | "bidirectional" | "passive" | "power";
export type Pin = { pin_id: string; instance_id: string; number: string; name: string; direction: PinDirection };
export type NetNode = { instance_id: string; pin_number: string };
export type Net = { net_id: string; name?: string | null; nodes: NetNode[] };
export type NetLabel = { net_id: string; label: string };
export type HierarchicalSheet = { sheet_id: string; name: string; parent_sheet_id?: string | null };
export type Annotation = { annotation_id: string; text: string; scope: string };
export type SchematicIR = {
  schema_version: SchemaVersion;
  symbols: Symbol[];
  component_instances: ComponentInstance[];
  pins: Pin[];
  nets: Net[];
  net_labels: NetLabel[];
  hierarchical_sheets: HierarchicalSheet[];
  annotations: Annotation[];
};

export type BoardOutline = { shape: string; dimensions_mm: Record<string, number> };
export type StackupLayer = { name: string; kind: string; thickness_um: number };
export type Footprint = { footprint_id: string; instance_id: string; package: string };
export type Constraint = { constraint_id: string; kind: string; expression: string };
export type NetClass = { name: string; nets: string[]; rules: Record<string, string | number> };
export type Region = { region_id: string; region_type: string; layers: string[] };
export type RoutingIntent = { net_or_group: string; intent: string };
export type BoardIR = {
  schema_version: SchemaVersion;
  board_outline: BoardOutline;
  stackup: StackupLayer[];
  footprints: Footprint[];
  placement_constraints: Constraint[];
  design_rules: Constraint[];
  net_classes: NetClass[];
  keepouts: Region[];
  zones: Region[];
  routing_intents: RoutingIntent[];
};

export type PatchOperation = { op: "add" | "update" | "remove" | "move"; path: string; value?: unknown };
export type PatchPlan = {
  schema_version: SchemaVersion;
  user_intent: string;
  affected_objects: string[];
  operations: PatchOperation[];
  impact_scope: "local" | "sheet" | "board" | "global";
  requires_confirmation: boolean;
};

export type Severity = "info" | "warning" | "error" | "critical";
export type Finding = { code: string; message: string; details: Record<string, unknown> };
export type VerificationReport = {
  schema_version: SchemaVersion;
  tool: string;
  severity: Severity;
  findings: Finding[];
  affected_objects: string[];
  suggested_fixes: string[];
};

export type CanonicalDesignBundle = {
  schema_version: SchemaVersion;
  circuit_spec: CircuitSpec;
  schematic_ir: SchematicIR;
  board_ir: BoardIR;
  patch_plan: PatchPlan;
  verification_report: VerificationReport;
};
"""


def main() -> None:
    JSON_OUT.mkdir(parents=True, exist_ok=True)

    for filename, model in MODELS.items():
        schema = model.model_json_schema()
        schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
        schema["$id"] = f"https://traceagent.dev/schemas/canonical/{filename}"
        (JSON_OUT / filename).write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")

    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(TS_TEMPLATE, encoding="utf-8")


if __name__ == "__main__":
    main()
